# Generated by Django 3.2.7 on 2021-10-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_image_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pics.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pics.location'),
        ),
    ]
